### ISSUE TITLE
Error when using matplotlib with usetex=True on jupyterlab/binder

### ISSUE THREAD

**Issue by PedroTayer** [binder-examples/latex#12]
Thanks for the repo. It was very useful for me.

I had problems when trying to use latex on matplotlib in jupyterlab/binder. A message "RuntimeError: latex was not able to process the following string" arised.

I think changing the `apt.txt` as showed in the [this comment](https://github.com/jupyterhub/binder/issues/211#issuecomment-847256679) from official Jupyter-Hub issues may solve the problem.

```
dvipng
ghostscript
texlive-fonts-recommended
texlive-generic-recommended
texlive-latex-base
texlive-latex-extra
texlive-latex-recommended
texlive-publishers
texlive-science
texlive-xetex
cm-super
```

I don't know if this file generates other types of bug but it seems to work.

Thanks,

Pedro

**Comment by choldgraf** [comment]
Thanks @PedroTayer ! Want to make a quick PR to update this repository? I'm happy to give it a look
