### ISSUE TITLE
latex image output  display broken?

### ISSUE THREAD

**Issue by psychemedia** [binder-examples/latex#2]
Noticing that some of my latex magics appear to have stopped working following rebuilds after a bi derhub update

**Comment by psychemedia** [comment]
(on mobile device and struggling. Can't edit previous in mobile UI?)
Noticing that some of my latex magics appear to have stopped working following rebuilds after a recent Binderhub update, (missing ghostscript?) I clined and built this repo and the demo notebook seems to break too when trying to render the latex image?

**Comment by choldgraf** [comment]
Huh - I'm not sure what this could be...we haven't changed the base image or the repositories in apt (at least that I know of). @betatim could this be related to the PRs that got merged into BinderHub to improve security and such? I can't remember what they were but I seem to remember some breaking things happening to BinderHub just before the holidays...

**Comment by yuvipanda** [comment]
We didn't do anything security related that would affect this.

**Comment by yuvipanda** [comment]
```
RuntimeError: LaTeX was not able to process the following string:
b'$\\\\LaTeX_{rulez}$!!!!!!'

Here is the full report generated by LaTeX:
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./06d8dcf5cdf17d86afe9f37edb6542ae.tex
LaTeX2e <2017/01/01> patch level 3
Babel <3.9r> and hyphenation patterns for 3 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (5058.9pt) is ignored.


Package geometry Warning: Over-specification in `v'-direction.
    `height' (5058.9pt) is ignored.

)
No file 06d8dcf5cdf17d86afe9f37edb6542ae.aux.
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
! You can't use `\spacefactor' in math mode.
\@->\spacefactor 
                 \@m {}
l.12 ...ze{30.000000}{37.500000}{\sffamily $\LaTeX
                                                  _{rulez}$!!!!!!}
[1] (./06d8dcf5cdf17d86afe9f37edb6542ae.aux) )
(see the transcript file for additional information)
Output written on 06d8dcf5cdf17d86afe9f37edb6542ae.dvi (1 page, 444 bytes).
Transcript written on 06d8dcf5cdf17d86afe9f37edb6542ae.log.
```

seems to be the actual error from Latex. Specifically it looks like `! You can't use `\spacefactor' in math mode.` is where the issue is. Needs someone with Tex knowledge to debug

**Comment by yuvipanda** [comment]
pinging @mpacer who is the person I know with the most Tex knowledge (I think). M, do any of these errors look familiar to you?

**Comment by mpacer** [comment]
No not familiar but it could be security related if it blocks \write18 from being set(I think) which is technically a security vulnerability(allows code execution; remembering that TeX is Turing complete) that is expected by many TeX packages :/

**Comment by mpacer** [comment]
However that error suggests that something was working in math mode and is now not working in math mode… _that_ shouldn’t be affected by security changes… that also shouldn’t be an error that is run into in the base image… why would it be?

**Comment by mpacer** [comment]
Oh you can’t use \LaTeX in math mode we have a fix; but I don’t see why that would break the build. Note we’ve a fix for this in nbconvert but I need to make a release…

But nbconvert isn’t even being called here; extremely strange that it would cause an error on its own.

**Comment by mpacer** [comment]
Note MathJax made a decision I disagree with at some point and decided to include LaTeX in math mode.

**Comment by yuvipanda** [comment]
The security things we changed probably refers to https://github.com/jupyterhub/mybinder.org-deploy/pull/229 and friends, which simply changed how docker socket was accessed. Should have no effect on built image contents, so I think that should be totally ruled out.

**Comment by yuvipanda** [comment]
I'm convinced this will be fixed by https://github.com/jupyter/repo2docker/pull/181

**Comment by yuvipanda** [comment]
Nope, seems unrelated!

**Comment by choldgraf** [comment]
I think this was, in fact, a problem w/ mathjax and the `\LaTeX` bit - I've modified so that `\LaTeX` is now outside of the dollar signs and it seems to work fine, so closing this one :-)
