### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by sje30** [binder-examples/latex#3]
When I run this example, at first the ipynb shows the LateX rules!!! text, but then when I re-run the bottom chunk (several times), I see the following error:

<img width="1163" alt="screen shot 2018-03-22 at 08 15 04" src="https://user-images.githubusercontent.com/1095067/37763599-76b582aa-2db7-11e8-9d6c-77eaa709956c.png">

**Comment by choldgraf** [comment]
hmmm, I think this one is actually matplotlib latex weirdness - if I remove the "$" symbols it works, so I'll update with this

**Comment by choldgraf** [comment]
I take it back! I think it was related to this problem: https://github.com/jupyter/nbconvert/issues/262

**Comment by choldgraf** [comment]
just tried it again and I think it's fixed, so closing this :-) re-open if it doesn't work for you!
